#server:
#  port: 8080
#  undertow:
#    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
#    # 每块buffer的空间大小,越小的空间被利用越充分
#    buffer-size: 512
#    # 是否分配的直接内存
#    direct-buffers: true
#    threads:
#      io: 4  # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
#      worker: 32 # 阻塞任务线程池, io*8当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.19.74:3306/omso2o
#    username: omso2o
#    password: omso2o
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialSize: 10
#    maxActive: 100
#    minIdle: 10
#      #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，
#      #如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
#    maxWati: 60000
#    useUnfairLock: true #使用非公平锁
#    minEvictableIdleTimeMillis: 300000
#    maxPoolPreparedStatementPerConnectionSize: 100
#    poolPreparedStatements: false #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
#    validationQuery: select 1 for dual
#    testOnBorrow: false
#    testOnReturn: false
#    testWhileIdle: true
#    filters: stat,wall
#    # sql合并，慢查询定义为5s
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 10.101.3.3:8848 #nacos注册中心地址，
#    sentinel:
#      transport:
#        dashboard: 192.168.32.36:8080   #配置Sentinel DashBoard地址
#        port: 8722                  #微服务向Sentinel控制台开发的端口
#        clientIp: 10.28.143.60      #解析；该配置项多用于多网卡环境，如果多网卡环境必须制定clientIp，否则就会Sentinel控制台有可能找不到
#  profiles:
#    active: dev
#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
#info:
#  app.name: lppz takeout version 3.0
#  company.name: lppz.com
#  build.artifactId: takeout3-cloud
#  build.version: 1.0.1-SNAPSHOT
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"